version: "3.7"
services:
  web:
    build: .
    ports:
      - "8000:4000"
    links:
      - database:mongodb
    depends_on:
      - database
  database:
    image: mongo
    ports:
      - "27017"
